version: 5.0.{build}

branches:
  only:
    - Extended

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}' 
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

image: Visual Studio 2022

before_build:
  - nuget restore DotNetProjects.Wpf.Extended.Toolkit.sln
  
build:
  project: DotNetProjects.Wpf.Extended.Toolkit.sln

test: off

artifacts:
  - path: Src\Xceed.Wpf.Toolkit\bin\Release\DotNetProjects.Wpf.Extended.Toolkit.dll
    name: DotNetProjects.Wpf.Extended.Toolkit.dll
  - path: Src\Xceed.Wpf.Toolkit\bin\Release\DotNetProjects.Wpf.Extended.Toolkit.pdb
    name: DotNetProjects.Wpf.Extended.Toolkit.pdb
  - path: Src\Xceed.Wpf.Toolkit\bin\Release\DotNetProjects.Wpf.DataGrid.dll
    name: DotNetProjects.Wpf.DataGrid.dll
  - path: Src\Xceed.Wpf.Toolkit\bin\Release\DotNetProjects.Wpf.DataGrid.pdb
    name: DotNetProjects.Wpf.DataGrid.pdb
  - path: '**\DotNetProjects.*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: KC79cwbPGXPstkkHjylej8XZl/4CKdENSy/SF0wnkuU6CV6fVkK2ivDm1WzrIgo7
  artifact: /.*\.nupkg/
  
  
  
